---
##
# Pools Wallet

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grinwallet
  labels:
    node: lucy
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/wallet
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lucy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grinwallet
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      node: lucy
---
##
# Pools Keybase Account

apiVersion: v1
kind: PersistentVolume
metadata:
  name: keybase
  labels:
    node: lucy
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/keybase
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - lucy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keybase
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      node: lucy
