apiVersion: v1
kind: Service
metadata:
  name: healthcheck
  labels:
    run: healthcheck
spec:
  type: LoadBalancer
  ports:
  - port: 32050
    nodePort: 32050
    protocol: TCP
    name: healthcheck
  selector:
    run: healthcheck
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: healthcheck
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: healthcheck
    spec:
      containers:
      - name: healthcheck
        image: docker.mwgrinpool.com:5001/services:latest
#        command: ["sleep", "9999"]
        command: ["/usr/local/bin/healthCheck.py"]
        ports:
        - containerPort: 32050
      imagePullSecrets:
      - name: regsecret

