apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: paymentestimator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: paymentestimator
    spec:
      containers:
      - name: grin-pool
        image: bitgrinmining/services:latest
        args: ["/usr/local/bin/paymentEstimator.py"]
        env:
        - name: DEBUG_HOLD
          value: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      imagePullSecrets:
      - name: regsecret

