---
apiVersion: v1
kind: Service
metadata:
  name: poolapi
  labels:
    run: poolapi
spec:
  ports:
  - port: 13423
    protocol: TCP
    name: poolapi
  selector:
    run: poolapi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: poolapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: poolapi
    spec:
      containers:
      - name: poolapi
        image: docker.mwgrinpool.com:5001/services:latest
        #command: ["/usr/local/bin/api/api.py"]
        #command: ["sleep", "9999"]
        command: ["gunicorn", "-w", "8", "--timeout", "999", "-b", "0.0.0.0:13423", "api.api:app"]
        ports:
        - containerPort: 13423
        env:
        - name: GRIN_POOL_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grinpool-admin
              key: username.txt
        - name: GRIN_POOL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grinpool-admin
              key: password.txt
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      imagePullSecrets:
      - name: regsecret
