apiVersion: v1
kind: Service
metadata:
  name: splunkui
  labels:
    run: splunk
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    protocol: TCP
    name: splunkweb
  selector:
    run: splunk
---
apiVersion: v1
kind: Service
metadata:
  name: splunk
  labels:
    run: splunk
spec:
  ports:
  - port: 9997
    protocol: TCP
    name: splunkrecvr
  selector:
    run: splunk
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: splunk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: splunk
    spec:
      containers:
      - name: splunk
        image: docker.mwgrinpool.com:5001/splunk:latest
        command: ["sleep", "9999999"]
#        command: ["/sbin/entrypoint.sh", "start"]
#        command: ["/run.sh"]
        ports:
        - containerPort: 8000
        - containerPort: 9997
        env:
        - name: SPLUNK_START_ARGS
          value: "--accept-license"
        - name: SPLUNK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: splunk
              key: password.txt
        volumeMounts:
        - name: splunk
          mountPath: /opt/splunk
      volumes:
      - name: splunk
        persistentVolumeClaim:
          claimName: splunk
      imagePullSecrets:
      - name: regsecret
