apiVersion: v1
kind: Service
metadata:
  name: stratum
  labels:
    run: stratum
spec:
  type: LoadBalancer
  loadBalancerIP: 35.195.176.190
  ports:
  - port: 3333
    name: stratum
    protocol: TCP
  selector:
    run: stratum
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: stratum
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: stratum
    spec:
      containers:
      - name: stratum
        image: bitgrinmining/stratum:latest
        command: ["/run.sh"]
        ports:
        - containerPort: 3333
        volumeMounts:
        - name: logdir
          mountPath: /stratum
      - name: sharewatcher
        image: bitgrinmining/logstash:latest
        command: ["/run.sh", "poolsharefilter.conf"]
        env:
        - name: RMQ_USER
          valueFrom:
            secretKeyRef:
              name: rmq
              key: username.txt
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmq
              key: password.txt
        volumeMounts:
        - name: logdir
          mountPath: /stratum
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: logdir
        emptyDir: {}

